"""Add new_username and new_password_hash columns

Revision ID: 8a3176fe5023
Revises: b13a49dd9d19
Create Date: 2023-11-21 09:16:07.696528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3176fe5023'
down_revision = 'b13a49dd9d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('new_password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('new_password_hash')
        batch_op.drop_column('new_username')

    # ### end Alembic commands ###
